package dna;

import java.util.List;

public abstract class DNAFeature {

	/**
	 * Appends the features generated by the respective class to the tokens' feature vector.
	 * @param tokens the tokens to have their feature vector expanded
	 * @return
	 */
	public abstract void buildFeature(List<DNAToken> tokens);
	/**
	 * The number of features/elements that are added to each token's feature vector.
	 * @return
	 */
	public abstract int numberOfFeatures();
	
}

